Pause Insert Software Laboratories Inc. DOS backup # 1 in drive G:
dir g:
erase g:*.*
copy c:sliboot.asm g:
copy c:slidos.asm g:
copy c:slipict.asm g:
copy c:sliboss.asm g:
copy c:slifmt.asm g:
copy slidos.com g:
copy slicomd.com g:
copy c:slidos.doc g:
copy slidlnk.lnk g:
copy sliclnk.lnk g:
Pause Insert Software Laboratories Inc. DOS backup # 2 in drive G:
dir g:
erase g:*.*
copy c:slifutl.asm g:
copy c:slidutl.asm g:
copy c:slidata.asm g:
copy c:slidata.inc g:
copy slidlk.bat g:
copy slidlknl.bat g:
copy sliclk.bat g:
copy sliclknl.bat g:
copy slisys.bat g:
copy slisysnl.bat g:
copy slibak.bat g:
copy sliboot.exe g:
